name = "banking"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BANK_KV"
id = "fa8bcc19366b4f68ac9c3ff6ebf54a0b"

[[d1_databases]]
binding = "BANK_DB"
database_name = "bank-database"
database_id = "6f12dd90-3093-4b25-adcb-a0e43ece88ac"
